# -*- coding: utf-8 -*-

from sqlalchemy import (
    MetaData, Table, Column, String, Numeric, Date, Integer, ForeignKey
)

from src.outils.chemins import dossier_config, dossier_xlsx_propres


# --------------------------------------------------------------------
# Déclaration des métadonnées pour chaque schéma
# --------------------------------------------------------------------
metadata_ventes  = MetaData(schema="Ventes")
metadata_achats  = MetaData(schema="Achats")

# --------------------------------------------------------------------
# Création des tables Ventes
# --------------------------------------------------------------------

# Table : FAMILLE (Ventes)
famille_ventes = Table(
    "FAMILLE", metadata_ventes,
    Column("FA_CODEFAMILLE", String, primary_key=True, quote=True),
    Column("FA_CENTRAL",   String, quote=True),
    Column("FA_INTITULE",  String, nullable=False, quote=True)
)

# Table : ARTICLES (Ventes)
articles_ventes = Table(
    "ARTICLES", metadata_ventes,
    Column("AR_REF",     String, primary_key=True, quote=True),
    Column("AR_DESIGN",  String, quote=True),
    Column("AR_PRIXACH", Numeric(10, 2), quote=True),
    Column("FA_CODEFAMILLE", String, ForeignKey("Ventes.FAMILLE.FA_CODEFAMILLE"), quote=True)
)

# Table : COMPTET (Ventes)
comptet_ventes = Table(
    "COMPTET", metadata_ventes,
    Column("CT_NUM",  String, primary_key=True, quote=True),
    Column("CT_INTITULE", String, quote=True),
    Column("BT_NUM",  String, quote=True),
    Column("CA_NUM",  String, quote=True),
    Column("CA_NUMIFRS", String, quote=True),
    Column("CBCREATEUR", String, quote=True),
    Column("CBMODIFICATION", String, quote=True),
    Column("CBREPLICATION", String, quote=True),
    Column("CG_NUMPRINC", String, quote=True),
    Column("CODE_HYPERIX_CHEZ_LE_CLIENT", String, quote=True),
    Column("CO_NO", String, quote=True),
    Column("CT_ADRESSE", String, quote=True),
    Column("CT_APE", String, quote=True),
    Column("CT_ASSURANCE", String, quote=True),
    Column("CT_BLFACT", String, quote=True),
    Column("CT_CLASSEMENT", String, quote=True),
    Column("CT_CODEPOSTAL", String, quote=True),
    Column("CT_CODEREGION", String, quote=True),
    Column("CT_COFACE", String, quote=True),
    Column("CT_COMMENTAIRE", String, quote=True),
    Column("CT_COMPLEMENT", String, quote=True),
    Column("CT_CONTACT", String, quote=True),
    Column("CT_CONTROLENC", String, quote=True),
    Column("CT_DATECREATE", String, quote=True),
    Column("CT_DATEFERMEDEBUT", String, quote=True),
    Column("CT_DATEFERMEFIN", String, quote=True),
    Column("CT_EDI1", String, quote=True),
    Column("CT_EDI2", String, quote=True),
    Column("CT_EDI3", String, quote=True),
    Column("CT_EMAIL", String, quote=True),
    Column("CT_ENCOURS", String, quote=True),
    Column("CT_FACTURE", String, quote=True),
    Column("CT_FACTUREELEC", String, quote=True),
    Column("CT_IDENTIFIANT", String, quote=True),
    Column("CT_LANGUE", String, quote=True),
    Column("CT_LETTRAGE", String, quote=True),
    Column("CT_LIVRPARTIELLE", String, quote=True),
    Column("CT_NOTPENAL", String, quote=True),
    Column("CT_NOTRAPPEL", String, quote=True),
    Column("CT_NUMCENTRALE", String, quote=True),
    Column("CT_NUMPAYEUR", String, quote=True),
    Column("CT_PAYS", String, quote=True),
    Column("CT_PRIORITELIVR", String, quote=True),
    Column("CT_QUALITE", String, quote=True),
    Column("CT_RACCOURCI", String, quote=True),
    Column("CT_REPRESENTINT", String, quote=True),
    Column("CT_REPRESENTNIF", String, quote=True),
    Column("CT_SAUT", String, quote=True),
    Column("CT_SIRET", String, quote=True),
    Column("CT_SITE", String, quote=True),
    Column("CT_SOMMEIL", String, quote=True),
    Column("CT_STATISTIQUE01", String, quote=True),
    Column("CT_STATISTIQUE02", String, quote=True),
    Column("CT_STATISTIQUE03", String, quote=True),
    Column("CT_STATISTIQUE04", String, quote=True),
    Column("CT_STATISTIQUE05", String, quote=True),
    Column("CT_STATISTIQUE06", String, quote=True),
    Column("CT_STATISTIQUE07", String, quote=True),
    Column("CT_STATISTIQUE08", String, quote=True),
    Column("CT_STATISTIQUE09", String, quote=True),
    Column("CT_STATISTIQUE10", String, quote=True),
    Column("CT_SURVEILLANCE", String, quote=True),
    Column("CT_SVCA", String, quote=True),
    Column("CT_SVCOTATION", String, quote=True),
    Column("CT_SVDATEBILAN", String, quote=True),
    Column("CT_SVDATECREATE", String, quote=True),
    Column("CT_SVDATEINCID", String, quote=True),
    Column("CT_SVDATEMAJ", String, quote=True),
    Column("CT_SVEFFECTIF", String, quote=True),
    Column("CT_SVFORMEJURI", String, quote=True),
    Column("CT_SVINCIDENT", String, quote=True),
    Column("CT_SVNBMOISBILAN", String, quote=True),
    Column("CT_SVOBJETMAJ", String, quote=True),
    Column("CT_SVPRIVIL", String, quote=True),
    Column("CT_SVREGUL", String, quote=True),
    Column("CT_SVRESULTAT", String, quote=True),
    Column("CT_TAUX01", String, quote=True),
    Column("CT_TAUX02", String, quote=True),
    Column("CT_TAUX03", String, quote=True),
    Column("CT_TAUX04", String, quote=True),
    Column("CT_TELECOPIE", String, quote=True),
    Column("CT_TELEPHONE", String, quote=True),
    Column("CT_TYPE", String, quote=True),
    Column("CT_TYPENIF", String, quote=True),
    Column("CT_VALIDECH", String, quote=True),
    Column("CT_VILLE", String, quote=True),
    Column("DE_NO", String, quote=True),
    Column("EB_NO", String, quote=True),
    Column("INT_ANALYTIQUE", String, quote=True),
    Column("INT_CATCOMPTA", String, quote=True),
    Column("INT_CATTARIF", String, quote=True),
    Column("INT_CONDITION", String, quote=True),
    Column("INT_DEVISE", String, quote=True),
    Column("INT_EXPEDITION", String, quote=True),
    Column("INT_PERIOD", String, quote=True),
    Column("INT_RISQUE", String, quote=True),
    Column("MR_NO", String, quote=True),
    Column("N_ANALYTIQUE", String, quote=True),
    Column("N_ANALYTIQUEIFRS", String, quote=True),
    Column("N_CATCOMPTA", String, quote=True),
    Column("N_CATTARIF", String, quote=True),
    Column("N_CONDITION", String, quote=True),
    Column("N_DEVISE", String, quote=True),
    Column("N_EXPEDITION", String, quote=True),
    Column("N_PERIOD", String, quote=True),
    Column("N_RISQUE", String, quote=True)
)

# Table : DOCLIGNE (Ventes)
docligne_ventes = Table(
    "DOCLIGNE", metadata_ventes,
    Column("DL_NO", String, primary_key=True, quote=True),
    Column("AC_REFCLIENT", String, quote=True),
    Column("AG_NO1", String, quote=True),
    Column("AG_NO2", String, quote=True),
    Column("AR_REF", String, ForeignKey("Ventes.ARTICLES.AR_REF"), quote=True),
    Column("AR_REFCOMPOSE", String, quote=True),
    Column("CA_NUM", String, quote=True),
    Column("CO_NO", String, quote=True),
    Column("CT_NUM", String, ForeignKey("Ventes.COMPTET.CT_NUM"), quote=True),
    Column("DE_NO", String, quote=True),
    Column("DLC", String, quote=True),
    Column("DLD", String, quote=True),
    Column("DL_CMUP", Numeric(10, 2), quote=True),
    Column("DL_DATEAVANCEMENT", String, quote=True),
    Column("DL_DATEBC", Date, quote=True),
    Column("DL_DATEBL", Date, quote=True),
    Column("DL_DATEPL", String, quote=True),
    Column("DL_DESIGN", String, quote=True),
    Column("DL_ESCOMPTE", String, quote=True),
    Column("DL_FACTPOIDS", String, quote=True),
    Column("DL_FRAIS", String, quote=True),
    Column("DL_LIGNE", String, quote=True),
    Column("DL_MONTANTHT", Numeric(10, 2), quote=True),
    Column("DL_MONTANTTTC", Numeric(10, 2), quote=True),
    Column("DL_MVTSTOCK", String, quote=True),
    Column("DL_NOCOLIS", String, quote=True),
    Column("DL_NOLINK", String, quote=True),
    Column("DL_NONLIVRE", String, quote=True),
    Column("DL_NOREF", String, quote=True),
    Column("DL_PIECEBC", String, quote=True),
    Column("DL_PIECEBL", String, quote=True),
    Column("DL_PIECEPL", String, quote=True),
    Column("DL_POIDSBRUT", Numeric(10, 2), quote=True),
    Column("DL_POIDSNET", Numeric(10, 2), quote=True),
    Column("DL_PRIXRU", Numeric(10, 2), quote=True),
    Column("DL_PRIXUNITAIRE", Numeric(10, 2), quote=True),
    Column("DL_PUBC", String, quote=True),
    Column("DL_PUDEVISE", Numeric(10, 2), quote=True),
    Column("DL_PUTTC", Numeric(10, 2), quote=True),
    Column("DL_QTE", Numeric(10, 2), quote=True),
    Column("DL_QTEBC", Numeric(10, 2), quote=True),
    Column("DL_QTEBL", Numeric(10, 2), quote=True),
    Column("DL_QTEPL", Numeric(10, 2), quote=True),
    Column("DL_QTERESSOURCE", Numeric(10, 2), quote=True),
    Column("DL_REMISE01REM_TYPE", String, quote=True),
    Column("DL_REMISE01REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_REMISE02REM_TYPE", String, quote=True),
    Column("DL_REMISE02REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_REMISE03REM_TYPE", String, quote=True),
    Column("DL_REMISE03REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_TAXE1", Numeric(10, 2), quote=True),
    Column("DL_TAXE2", Numeric(10, 2), quote=True),
    Column("DL_TAXE3", Numeric(10, 2), quote=True),
    Column("DL_TNOMENCL", String, quote=True),
    Column("DL_TREMEXEP", String, quote=True),
    Column("DL_TREMPIED", String, quote=True),
    Column("DL_TTC", Numeric(10, 2), quote=True),
    Column("DL_TYPEPL", String, quote=True),
    Column("DL_TYPETAUX1", String, quote=True),
    Column("DL_TYPETAUX2", String, quote=True),
    Column("DL_TYPETAUX3", String, quote=True),
    Column("DL_TYPETAXE1", String, quote=True),
    Column("DL_TYPETAXE2", String, quote=True),
    Column("DL_TYPETAXE3", String, quote=True),
    Column("DL_VALORISE", String, quote=True),

    Column("DO_DATE", Date, quote=True),
    Column("DO_DATELIVR", Date, quote=True),
    Column("DO_DOMAINE", String, quote=True),
    Column("DO_PIECE", String, quote=True),
    Column("DO_REF", String, quote=True),
    Column("DO_TYPE", String, quote=True),

    Column("DT_NO", String, quote=True),
    Column("EU_ENUMERE", String, quote=True),
    Column("EU_QTE", Numeric(10, 2), quote=True),

    Column("FNT_MONTANTHT", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTHTSIGNE", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTAXES", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTTC", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTTCSIGNE", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNET", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNETDEVISE", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNETTTC", Numeric(10, 2), quote=True),
    Column("FNT_QTESIGNE", Numeric(10, 2), quote=True),
    Column("FNT_REMISEGLOBALE", Numeric(10, 2), quote=True),

    Column("LS_COMPLEMENT", String, quote=True),
    Column("LS_FABRICATION", String, quote=True),
    Column("LS_NOSERIE", String, quote=True),
    Column("LS_PEREMPTION", String, quote=True),

    Column("N°_DE_LOT/_CURE_DATE", String, quote=True),
    Column("QTE_ACCESS", Numeric(10, 2), quote=True),
    Column("RP_CODE", String, quote=True)
)

# --------------------------------------------------------------------
# Création des tables Achats
# --------------------------------------------------------------------
# Table : FAMILLE (Achats)
famille_achats = Table(
    "FAMILLE", metadata_achats,
    Column("FA_CODEFAMILLE", String, primary_key=True, quote=True),
    Column("FA_CENTRAL", String, quote=True),
    Column("FA_INTITULE", String, nullable=False, quote=True)
)

# Table : ARTICLES (Achats)
articles_achats = Table(
    "ARTICLES", metadata_achats,
    Column("AR_REF", String, primary_key=True, quote=True),
    Column("AR_DESIGN", String, quote=True),
    Column("AR_PRIXACH", Numeric(10, 2), quote=True),
    Column("FA_CODEFAMILLE", String, ForeignKey("Achats.FAMILLE.FA_CODEFAMILLE"), quote=True)
)

# Table : COMPTET (Achats)
comptet_achats = Table(
    "COMPTET", metadata_achats,
    Column("CT_NUM", String, primary_key=True, quote=True),
    Column("CT_INTITULE", String, quote=True),
    Column("BT_NUM", String, quote=True),
    Column("CA_NUM", String, quote=True),
    Column("CA_NUMIFRS", String, quote=True),
    Column("CBCREATEUR", String, quote=True),
    Column("CBMODIFICATION", String, quote=True),
    Column("CBREPLICATION", String, quote=True),
    Column("CG_NUMPRINC", String, quote=True),
    Column("CODE_HYPERIX_CHEZ_LE_CLIENT", String, quote=True),
    Column("CO_NO", String, quote=True),
    Column("CT_ADRESSE", String, quote=True),
    Column("CT_APE", String, quote=True),
    Column("CT_ASSURANCE", String, quote=True),
    Column("CT_BLFACT", String, quote=True),
    Column("CT_CLASSEMENT", String, quote=True),
    Column("CT_CODEPOSTAL", String, quote=True),
    Column("CT_CODEREGION", String, quote=True),
    Column("CT_COFACE", String, quote=True),
    Column("CT_COMMENTAIRE", String, quote=True),
    Column("CT_COMPLEMENT", String, quote=True),
    Column("CT_CONTACT", String, quote=True),
    Column("CT_CONTROLENC", String, quote=True),
    Column("CT_DATECREATE", String, quote=True),
    Column("CT_DATEFERMEDEBUT", String, quote=True),
    Column("CT_DATEFERMEFIN", String, quote=True),
    Column("CT_EDI1", String, quote=True),
    Column("CT_EDI2", String, quote=True),
    Column("CT_EDI3", String, quote=True),
    Column("CT_EMAIL", String, quote=True),
    Column("CT_ENCOURS", String, quote=True),
    Column("CT_FACTURE", String, quote=True),
    Column("CT_FACTUREELEC", String, quote=True),
    Column("CT_IDENTIFIANT", String, quote=True),
    Column("CT_LANGUE", String, quote=True),
    Column("CT_LETTRAGE", String, quote=True),
    Column("CT_LIVRPARTIELLE", String, quote=True),
    Column("CT_NOTPENAL", String, quote=True),
    Column("CT_NOTRAPPEL", String, quote=True),
    Column("CT_NUMCENTRALE", String, quote=True),
    Column("CT_NUMPAYEUR", String, quote=True),
    Column("CT_PAYS", String, quote=True),
    Column("CT_PRIORITELIVR", String, quote=True),
    Column("CT_QUALITE", String, quote=True),
    Column("CT_RACCOURCI", String, quote=True),
    Column("CT_REPRESENTINT", String, quote=True),
    Column("CT_REPRESENTNIF", String, quote=True),
    Column("CT_SAUT", String, quote=True),
    Column("CT_SIRET", String, quote=True),
    Column("CT_SITE", String, quote=True),
    Column("CT_SOMMEIL", String, quote=True),
    Column("CT_STATISTIQUE01", String, quote=True),
    Column("CT_STATISTIQUE02", String, quote=True),
    Column("CT_STATISTIQUE03", String, quote=True),
    Column("CT_STATISTIQUE04", String, quote=True),
    Column("CT_STATISTIQUE05", String, quote=True),
    Column("CT_STATISTIQUE06", String, quote=True),
    Column("CT_STATISTIQUE07", String, quote=True),
    Column("CT_STATISTIQUE08", String, quote=True),
    Column("CT_STATISTIQUE09", String, quote=True),
    Column("CT_STATISTIQUE10", String, quote=True),
    Column("CT_SURVEILLANCE", String, quote=True),
    Column("CT_SVCA", String, quote=True),
    Column("CT_SVCOTATION", String, quote=True),
    Column("CT_SVDATEBILAN", String, quote=True),
    Column("CT_SVDATECREATE", String, quote=True),
    Column("CT_SVDATEINCID", String, quote=True),
    Column("CT_SVDATEMAJ", String, quote=True),
    Column("CT_SVEFFECTIF", String, quote=True),
    Column("CT_SVFORMEJURI", String, quote=True),
    Column("CT_SVINCIDENT", String, quote=True),
    Column("CT_SVNBMOISBILAN", String, quote=True),
    Column("CT_SVOBJETMAJ", String, quote=True),
    Column("CT_SVPRIVIL", String, quote=True),
    Column("CT_SVREGUL", String, quote=True),
    Column("CT_SVRESULTAT", String, quote=True),
    Column("CT_TAUX01", String, quote=True),
    Column("CT_TAUX02", String, quote=True),
    Column("CT_TAUX03", String, quote=True),
    Column("CT_TAUX04", String, quote=True),
    Column("CT_TELECOPIE", String, quote=True),
    Column("CT_TELEPHONE", String, quote=True),
    Column("CT_TYPE", String, quote=True),
    Column("CT_TYPENIF", String, quote=True),
    Column("CT_VALIDECH", String, quote=True),
    Column("CT_VILLE", String, quote=True),
    Column("DE_NO", String, quote=True),
    Column("EB_NO", String, quote=True),
    Column("INT_ANALYTIQUE", String, quote=True),
    Column("INT_CATCOMPTA", String, quote=True),
    Column("INT_CATTARIF", String, quote=True),
    Column("INT_CONDITION", String, quote=True),
    Column("INT_DEVISE", String, quote=True),
    Column("INT_EXPEDITION", String, quote=True),
    Column("INT_PERIOD", String, quote=True),
    Column("INT_RISQUE", String, quote=True),
    Column("MR_NO", String, quote=True),
    Column("N_ANALYTIQUE", String, quote=True),
    Column("N_ANALYTIQUEIFRS", String, quote=True),
    Column("N_CATCOMPTA", String, quote=True),
    Column("N_CATTARIF", String, quote=True),
    Column("N_CONDITION", String, quote=True),
    Column("N_DEVISE", String, quote=True),
    Column("N_EXPEDITION", String, quote=True),
    Column("N_PERIOD", String, quote=True),
    Column("N_RISQUE", String, quote=True)
)

# Table : ARTFOURNISS (Achats)
fournisseur_achats = Table(
    "ARTFOURNISS", metadata_achats,
    Column("AF_REFFOURNISS", String, primary_key=True, quote=True),
    Column("AF_CODEBARRE", String, quote=True),
    Column("AF_COLISAGE", String, quote=True),
    Column("AF_CONVDIV", String, quote=True),
    Column("AF_CONVERSION", String, quote=True),
    Column("AF_DATEAPPLICATION", Date, quote=True),
    Column("AF_DELAIAPPRO", Integer, quote=True),
    Column("AF_DEVISE", String, quote=True),
    Column("AF_GARANTIE", String, quote=True),
    Column("AF_PRINCIPAL", String, quote=True),
    Column("AF_PRIXACH", Numeric(10, 2), quote=True),
    Column("AF_PRIXACHNOUV", Numeric(10, 2), quote=True),
    Column("AF_PRIXDEV", Numeric(10, 2), quote=True),
    Column("AF_PRIXDEVNOUV", Numeric(10, 2), quote=True),
    Column("AF_QTEMINI", Numeric(10, 2), quote=True),
    Column("AF_QTEMONT", Numeric(10, 2), quote=True),
    Column("AF_REMISE", Numeric(10, 2), quote=True),
    Column("AF_REMISENOUV", Numeric(10, 2), quote=True),
    Column("AF_TYPEREM", String, quote=True),
    Column("AF_UNITE", String, quote=True),
    Column("AR_REF", String, ForeignKey("Achats.ARTICLES.AR_REF"), quote=True),
    Column("CT_NUM", String, quote=True),
    Column("EG_CHAMP", String, quote=True),
    Column("INT_CHAMP", String, quote=True),
    Column("INT_DEVISE", String, quote=True),
    Column("INT_UNITE", String, quote=True),
    Column("CBCREATEUR", String, quote=True),
    Column("CBMODIFICATION", String, quote=True),
    Column("CBREPLICATION", String, quote=True)
)

# Table : DOCLIGNE (Achats)
docligne_achats = Table(
    "DOCLIGNE", metadata_achats,
    Column("DL_NO", String, primary_key=True, quote=True),
    Column("AC_REFCLIENT", String, quote=True),
    Column("AF_REFFOURNISS", String, ForeignKey("Achats.ARTFOURNISS.AF_REFFOURNISS"), quote=True),
    Column("AG_NO1", String, quote=True),
    Column("AG_NO2", String, quote=True),
    Column("AR_REF", String, ForeignKey("Achats.ARTICLES.AR_REF"), quote=True),
    Column("AR_REFCOMPOSE", String, quote=True),
    Column("CA_NUM", String, quote=True),
    Column("CO_NO", String, quote=True),
    Column("CT_NUM", String, ForeignKey("Achats.COMPTET.CT_NUM"), quote=True),
    Column("DE_NO", String, quote=True),
    Column("DLC", String, quote=True),
    Column("DLD", String, quote=True),
    Column("DL_CMUP", Numeric(10, 2), quote=True),
    Column("DL_DATEAVANCEMENT", String, quote=True),
    Column("DL_DATEBC", Date, quote=True),
    Column("DL_DATEBL", Date, quote=True),
    Column("DL_DATEPL", String, quote=True),
    Column("DL_DESIGN", String, quote=True),
    Column("DL_ESCOMPTE", String, quote=True),
    Column("DL_FACTPOIDS", String, quote=True),
    Column("DL_FRAIS", String, quote=True),
    Column("DL_LIGNE", String, quote=True),
    Column("DL_MONTANTHT", Numeric(10, 2), quote=True),
    Column("DL_MONTANTTTC", Numeric(10, 2), quote=True),
    Column("DL_MVTSTOCK", String, quote=True),
    Column("DL_NOCOLIS", String, quote=True),
    Column("DL_NOLINK", String, quote=True),
    Column("DL_NONLIVRE", String, quote=True),
    Column("DL_NOREF", String, quote=True),
    Column("DL_PIECEBC", String, quote=True),
    Column("DL_PIECEBL", String, quote=True),
    Column("DL_PIECEPL", String, quote=True),
    Column("DL_POIDSBRUT", Numeric(10, 2), quote=True),
    Column("DL_POIDSNET", Numeric(10, 2), quote=True),
    Column("DL_PRIXRU", Numeric(10, 2), quote=True),
    Column("DL_PRIXUNITAIRE", Numeric(10, 2), quote=True),
    Column("DL_PUBC", String, quote=True),
    Column("DL_PUDEVISE", Numeric(10, 2), quote=True),
    Column("DL_PUTTC", Numeric(10, 2), quote=True),
    Column("DL_QTE", Numeric(10, 2), quote=True),
    Column("DL_QTEBC", Numeric(10, 2), quote=True),
    Column("DL_QTEBL", Numeric(10, 2), quote=True),
    Column("DL_QTEPL", Numeric(10, 2), quote=True),
    Column("DL_QTERESSOURCE", Numeric(10, 2), quote=True),
    Column("DL_REMISE01REM_TYPE", String, quote=True),
    Column("DL_REMISE01REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_REMISE02REM_TYPE", String, quote=True),
    Column("DL_REMISE02REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_REMISE03REM_TYPE", String, quote=True),
    Column("DL_REMISE03REM_VALEUR", Numeric(10, 2), quote=True),
    Column("DL_TAXE1", Numeric(10, 2), quote=True),
    Column("DL_TAXE2", Numeric(10, 2), quote=True),
    Column("DL_TAXE3", Numeric(10, 2), quote=True),
    Column("DL_TNOMENCL", String, quote=True),
    Column("DL_TREMEXEP", String, quote=True),
    Column("DL_TREMPIED", String, quote=True),
    Column("DL_TTC", Numeric(10, 2), quote=True),
    Column("DL_TYPEPL", String, quote=True),
    Column("DL_TYPETAUX1", String, quote=True),
    Column("DL_TYPETAUX2", String, quote=True),
    Column("DL_TYPETAUX3", String, quote=True),
    Column("DL_TYPETAXE1", String, quote=True),
    Column("DL_TYPETAXE2", String, quote=True),
    Column("DL_TYPETAXE3", String, quote=True),
    Column("DL_VALORISE", String, quote=True),

    Column("DO_DATE", Date, quote=True),
    Column("DO_DATELIVR", Date, quote=True),
    Column("DO_DOMAINE", String, quote=True),
    Column("DO_PIECE", String, quote=True),
    Column("DO_REF", String, quote=True),
    Column("DO_TYPE", String, quote=True),

    Column("DT_NO", String, quote=True),
    Column("EU_ENUMERE", String, quote=True),
    Column("EU_QTE", Numeric(10, 2), quote=True),

    Column("FNT_MONTANTHT", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTHTSIGNE", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTAXES", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTTC", Numeric(10, 2), quote=True),
    Column("FNT_MONTANTTTCSIGNE", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNET", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNETDEVISE", Numeric(10, 2), quote=True),
    Column("FNT_PRIXUNETTTC", Numeric(10, 2), quote=True),
    Column("FNT_QTESIGNE", Numeric(10, 2), quote=True),
    Column("FNT_REMISEGLOBALE", Numeric(10, 2), quote=True),

    Column("LS_COMPLEMENT", String, quote=True),
    Column("LS_FABRICATION", String, quote=True),
    Column("LS_NOSERIE", String, quote=True),
    Column("LS_PEREMPTION", String, quote=True),

    Column("N°_DE_LOT/_CURE_DATE", String, quote=True),
    Column("QTE_ACCESS", Numeric(10, 2), quote=True),
    Column("RP_CODE", String, quote=True)
)