# src/models/tables.py
# -*- coding: utf-8 -*-

from sqlalchemy import (
    MetaData, Table, Column, String, Numeric, Integer, ForeignKey, TIMESTAMP
)

# --------------------------------------------------------------------
# Déclaration des métadonnées SANS information de schéma
# --------------------------------------------------------------------
metadata_ventes = MetaData()
metadata_achats = MetaData()

# --------------------------------------------------------------------
# Création des tables Ventes
# --------------------------------------------------------------------

famille_ventes = Table(
    "FAMILLE", metadata_ventes,
    Column("FA_CODEFAMILLE", String(50), primary_key=True, quote=True),
    Column("FA_CENTRAL",   String(50), quote=True),
    Column("FA_INTITULE",  String(255), nullable=False, quote=True)
)

articles_ventes = Table(
    "ARTICLES", metadata_ventes,
    Column("AR_REF",     String(50), primary_key=True, quote=True),
    Column("AR_DESIGN",  String(255), quote=True),
    Column("AR_PRIXACH", Numeric(20, 6), quote=True),
    Column("FA_CODEFAMILLE", String(50), ForeignKey("FAMILLE.FA_CODEFAMILLE"), quote=True)
)

comptet_ventes = Table(
    "COMPTET", metadata_ventes,
    Column("CT_NUM",  String(50), primary_key=True, quote=True),
    Column("CT_INTITULE", String(255), quote=True),
    Column("BT_NUM",  String(50), quote=True),
    Column("CA_NUM",  String(50), quote=True),
    Column("CA_NUMIFRS", String(50), quote=True),
    Column("CBCREATEUR", String(50), quote=True),
    Column("CBMODIFICATION", TIMESTAMP, quote=True),
    Column("CBREPLICATION", Integer, quote=True),
    Column("CG_NUMPRINC", String(50), quote=True),
    Column("CODE_HYPERIX_CHEZ_LE_CLIENT", String(255), quote=True),
    Column("CO_NO", Integer, quote=True),
    Column("CT_ADRESSE", String(255), quote=True),
    Column("CT_APE", String(50), quote=True),
    Column("CT_ASSURANCE", String(255), quote=True),
    Column("CT_BLFACT", Integer, quote=True),
    Column("CT_CLASSEMENT", String(50), quote=True),
    Column("CT_CODEPOSTAL", String(20), quote=True),
    Column("CT_CODEREGION", String(50), quote=True),
    Column("CT_COFACE", String(255), quote=True),
    Column("CT_COMMENTAIRE", String(1024), quote=True),
    Column("CT_COMPLEMENT", String(255), quote=True),
    Column("CT_CONTACT", String(255), quote=True),
    Column("CT_CONTROLENC", Integer, quote=True),
    Column("CT_DATECREATE", TIMESTAMP, quote=True),
    Column("CT_DATEFERMEDEBUT", TIMESTAMP, quote=True),
    Column("CT_DATEFERMEFIN", TIMESTAMP, quote=True),
    Column("CT_EDI1", String(255), quote=True),
    Column("CT_EDI2", String(255), quote=True),
    Column("CT_EDI3", String(255), quote=True),
    Column("CT_EMAIL", String(255), quote=True),
    Column("CT_ENCOURS", Numeric(20, 6), quote=True),
    Column("CT_FACTURE", Integer, quote=True),
    Column("CT_FACTUREELEC", Integer, quote=True),
    Column("CT_IDENTIFIANT", String(50), quote=True),
    Column("CT_LANGUE", Integer, quote=True),
    Column("CT_LETTRAGE", Integer, quote=True),
    Column("CT_LIVRPARTIELLE", Integer, quote=True),
    Column("CT_NOTPENAL", Integer, quote=True),
    Column("CT_NOTRAPPEL", Integer, quote=True),
    Column("CT_NUMCENTRALE", String(50), quote=True),
    Column("CT_NUMPAYEUR", String(50), quote=True),
    Column("CT_PAYS", String(50), quote=True),
    Column("CT_PRIORITELIVR", Integer, quote=True),
    Column("CT_QUALITE", String(50), quote=True),
    Column("CT_RACCOURCI", String(50), quote=True),
    Column("CT_REPRESENTINT", String(50), quote=True),
    Column("CT_REPRESENTNIF", String(50), quote=True),
    Column("CT_SAUT", Integer, quote=True),
    Column("CT_SIRET", String(50), quote=True),
    Column("CT_SITE", String(255), quote=True),
    Column("CT_SOMMEIL", Integer, quote=True),
    Column("CT_STATISTIQUE01", String(50), quote=True),
    Column("CT_STATISTIQUE02", String(50), quote=True),
    Column("CT_STATISTIQUE03", String(50), quote=True),
    Column("CT_STATISTIQUE04", String(50), quote=True),
    Column("CT_STATISTIQUE05", String(50), quote=True),
    Column("CT_STATISTIQUE06", String(50), quote=True),
    Column("CT_STATISTIQUE07", String(50), quote=True),
    Column("CT_STATISTIQUE08", String(50), quote=True),
    Column("CT_STATISTIQUE09", String(50), quote=True),
    Column("CT_STATISTIQUE10", String(50), quote=True),
    Column("CT_SURVEILLANCE", Integer, quote=True),
    Column("CT_SVCA", Numeric(20, 6), quote=True),
    Column("CT_SVCOTATION", Integer, quote=True),
    Column("CT_SVDATEBILAN", TIMESTAMP, quote=True),
    Column("CT_SVDATECREATE", TIMESTAMP, quote=True),
    Column("CT_SVDATEINCID", TIMESTAMP, quote=True),
    Column("CT_SVDATEMAJ", TIMESTAMP, quote=True),
    Column("CT_SVEFFECTIF", Integer, quote=True),
    Column("CT_SVFORMEJURI", String(255), quote=True),
    Column("CT_SVINCIDENT", Integer, quote=True),
    Column("CT_SVNBMOISBILAN", Integer, quote=True),
    Column("CT_SVOBJETMAJ", String(255), quote=True),
    Column("CT_SVPRIVIL", Integer, quote=True),
    Column("CT_SVREGUL", Integer, quote=True),
    Column("CT_SVRESULTAT", Numeric(20, 6), quote=True),
    Column("CT_TAUX01", Numeric(20, 6), quote=True),
    Column("CT_TAUX02", Numeric(20, 6), quote=True),
    Column("CT_TAUX03", Numeric(20, 6), quote=True),
    Column("CT_TAUX04", Numeric(20, 6), quote=True),
    Column("CT_TELECOPIE", String(50), quote=True),
    Column("CT_TELEPHONE", String(50), quote=True),
    Column("CT_TYPE", Integer, quote=True),
    Column("CT_TYPENIF", Integer, quote=True),
    Column("CT_VALIDECH", Integer, quote=True),
    Column("CT_VILLE", String(255), quote=True),
    Column("DE_NO", Integer, quote=True),
    Column("EB_NO", Integer, quote=True),
    Column("INT_ANALYTIQUE", String(50), quote=True),
    Column("INT_CATCOMPTA", String(50), quote=True),
    Column("INT_CATTARIF", String(50), quote=True),
    Column("INT_CONDITION", String(50), quote=True),
    Column("INT_DEVISE", String(50), quote=True),
    Column("INT_EXPEDITION", String(50), quote=True),
    Column("INT_PERIOD", String(50), quote=True),
    Column("INT_RISQUE", String(50), quote=True),
    Column("MR_NO", Integer, quote=True),
    Column("N_ANALYTIQUE", String(50), quote=True),
    Column("N_ANALYTIQUEIFRS", String(50), quote=True),
    Column("N_CATCOMPTA", Integer, quote=True),
    Column("N_CATTARIF", Integer, quote=True),
    Column("N_CONDITION", Integer, quote=True),
    Column("N_DEVISE", Integer, quote=True),
    Column("N_EXPEDITION", Integer, quote=True),
    Column("N_PERIOD", Integer, quote=True),
    Column("N_RISQUE", Integer, quote=True)
)

docligne_ventes = Table(
    "DOCLIGNE", metadata_ventes,
    Column("DL_NO", Integer, primary_key=True, quote=True),
    Column("AC_REFCLIENT", String(255), quote=True),
    Column("AG_NO1", Integer, quote=True),
    Column("AG_NO2", Integer, quote=True),
    Column("AR_REF", String(50), ForeignKey("ARTICLES.AR_REF"), quote=True),
    Column("AR_REFCOMPOSE", String(50), quote=True),
    Column("CA_NUM", String(50), quote=True),
    Column("CO_NO", Integer, quote=True),
    Column("CT_NUM", String(50), ForeignKey("COMPTET.CT_NUM"), quote=True),
    Column("DE_NO", Integer, quote=True),
    Column("DLC", TIMESTAMP, quote=True),
    Column("DLD", TIMESTAMP, quote=True),
    Column("DL_CMUP", Numeric(20, 6), quote=True),
    Column("DL_DATEAVANCEMENT", TIMESTAMP, quote=True),
    Column("DL_DATEBC", TIMESTAMP, quote=True),
    Column("DL_DATEBL", TIMESTAMP, quote=True),
    Column("DL_DATEPL", TIMESTAMP, quote=True),
    Column("DL_DESIGN", String(255), quote=True),
    Column("DL_ESCOMPTE", Integer, quote=True),
    Column("DL_FACTPOIDS", Integer, quote=True),
    Column("DL_FRAIS", Integer, quote=True),
    Column("DL_LIGNE", Integer, quote=True),
    Column("DL_MONTANTHT", Numeric(20, 6), quote=True),
    Column("DL_MONTANTTTC", Numeric(20, 6), quote=True),
    Column("DL_MVTSTOCK", Integer, quote=True),
    Column("DL_NOCOLIS", String(50), quote=True),
    Column("DL_NOLINK", Integer, quote=True),
    Column("DL_NONLIVRE", Integer, quote=True),
    Column("DL_NOREF", Integer, quote=True),
    Column("DL_PIECEBC", String(50), quote=True),
    Column("DL_PIECEBL", String(50), quote=True),
    Column("DL_PIECEPL", String(50), quote=True),
    Column("DL_POIDSBRUT", Numeric(20, 6), quote=True),
    Column("DL_POIDSNET", Numeric(20, 6), quote=True),
    Column("DL_PRIXRU", Numeric(20, 6), quote=True),
    Column("DL_PRIXUNITAIRE", Numeric(20, 6), quote=True),
    Column("DL_PUBC", Numeric(20, 6), quote=True),
    Column("DL_PUDEVISE", Numeric(20, 6), quote=True),
    Column("DL_PUTTC", Numeric(20, 6), quote=True),
    Column("DL_QTE", Numeric(20, 6), quote=True),
    Column("DL_QTEBC", Numeric(20, 6), quote=True),
    Column("DL_QTEBL", Numeric(20, 6), quote=True),
    Column("DL_QTEPL", Numeric(20, 6), quote=True),
    Column("DL_QTERESSOURCE", Numeric(20, 6), quote=True),
    Column("DL_REMISE01REM_TYPE", Integer, quote=True),
    Column("DL_REMISE01REM_VALEUR", Numeric(20, 6), quote=True),
    Column("DL_REMISE02REM_TYPE", Integer, quote=True),
    Column("DL_REMISE02REM_VALEUR", Numeric(20, 6), quote=True),
    Column("DL_REMISE03REM_TYPE", Integer, quote=True),
    Column("DL_REMISE03REM_VALEUR", Numeric(20, 6), quote=True),
    Column("DL_TAXE1", Numeric(20, 6), quote=True),
    Column("DL_TAXE2", Numeric(20, 6), quote=True),
    Column("DL_TAXE3", Numeric(20, 6), quote=True),
    Column("DL_TNOMENCL", String(50), quote=True),
    Column("DL_TREMEXEP", Integer, quote=True),
    Column("DL_TREMPIED", Integer, quote=True),
    Column("DL_TTC", Integer, quote=True),
    Column("DL_TYPEPL", Integer, quote=True),
    Column("DL_TYPETAUX1", String(50), quote=True),
    Column("DL_TYPETAUX2", String(50), quote=True),
    Column("DL_TYPETAUX3", String(50), quote=True),
    Column("DL_TYPETAXE1", String(50), quote=True),
    Column("DL_TYPETAXE2", String(50), quote=True),
    Column("DL_TYPETAXE3", String(50), quote=True),
    Column("DL_VALORISE", Integer, quote=True),
    Column("DO_DATE", TIMESTAMP, quote=True),
    Column("DO_DATELIVR", TIMESTAMP, quote=True),
    Column("DO_DOMAINE", Integer, quote=True),
    Column("DO_PIECE", String(50), quote=True),
    Column("DO_REF", String(255), quote=True),
    Column("DO_TYPE", Integer, quote=True),
    Column("DT_NO", Integer, quote=True),
    Column("EU_ENUMERE", String(50), quote=True),
    Column("EU_QTE", Numeric(20, 6), quote=True),
    Column("FNT_MONTANTHT", Numeric(20, 6), quote=True),
    Column("FNT_MONTANTHTSIGNE", Numeric(20, 6), quote=True),
    Column("FNT_MONTANTTAXES", Numeric(20, 6), quote=True),
    Column("FNT_MONTANTTTC", Numeric(20, 6), quote=True),
    Column("FNT_MONTANTTTCSIGNE", Numeric(20, 6), quote=True),
    Column("FNT_PRIXUNET", Numeric(20, 6), quote=True),
    Column("FNT_PRIXUNETDEVISE", Numeric(20, 6), quote=True),
    Column("FNT_PRIXUNETTTC", Numeric(20, 6), quote=True),
    Column("FNT_QTESIGNE", Numeric(20, 6), quote=True),
    Column("FNT_REMISEGLOBALE", Numeric(20, 6), quote=True),
    Column("LS_COMPLEMENT", String(255), quote=True),
    Column("LS_FABRICATION", TIMESTAMP, quote=True),
    Column("LS_NOSERIE", String(50), quote=True),
    Column("LS_PEREMPTION", TIMESTAMP, quote=True),
    Column("N°_DE_LOT/_CURE_DATE", String(50), quote=True),
    Column("QTE_ACCESS", Numeric(20, 6), quote=True),
    Column("RP_CODE", String(50), quote=True)
)

# --------------------------------------------------------------------
# Création des tables Achats (réutilisation des définitions)
# --------------------------------------------------------------------
famille_achats = famille_ventes.to_metadata(metadata_achats)
articles_achats = articles_ventes.to_metadata(metadata_achats)
comptet_achats = comptet_ventes.to_metadata(metadata_achats)

fournisseur_achats = Table(
    "ARTFOURNISS", metadata_achats,
    Column("AF_REFFOURNISS", String(50), primary_key=True, quote=True),
    Column("AF_CODEBARRE", String(50), quote=True),
    Column("AF_COLISAGE", Numeric(20, 6), quote=True),
    Column("AF_CONVDIV", Integer, quote=True),
    Column("AF_CONVERSION", Numeric(20, 6), quote=True),
    Column("AF_DATEAPPLICATION", TIMESTAMP, quote=True),
    Column("AF_DELAIAPPRO", Integer, quote=True),
    Column("AF_DEVISE", Integer, quote=True),
    Column("AF_GARANTIE", Integer, quote=True),
    Column("AF_PRINCIPAL", Integer, quote=True),
    Column("AF_PRIXACH", Numeric(20, 6), quote=True),
    Column("AF_PRIXACHNOUV", Numeric(20, 6), quote=True),
    Column("AF_PRIXDEV", Numeric(20, 6), quote=True),
    Column("AF_PRIXDEVNOUV", Numeric(20, 6), quote=True),
    Column("AF_QTEMINI", Numeric(20, 6), quote=True),
    Column("AF_QTEMONT", Numeric(20, 6), quote=True),
    Column("AF_REMISE", Numeric(20, 6), quote=True),
    Column("AF_REMISENOUV", Numeric(20, 6), quote=True),
    Column("AF_TYPEREM", Integer, quote=True),
    Column("AF_UNITE", String(50), quote=True),
    Column("AR_REF", String(50), ForeignKey("ARTICLES.AR_REF"), quote=True),
    Column("CT_NUM", String(50), quote=True),
    Column("EG_CHAMP", Integer, quote=True),
    Column("INT_CHAMP", Integer, quote=True),
    Column("INT_DEVISE", Integer, quote=True),
    Column("INT_UNITE", Integer, quote=True),
    Column("CBCREATEUR", String(50), quote=True),
    Column("CBMODIFICATION", TIMESTAMP, quote=True),
    Column("CBREPLICATION", Integer, quote=True)
)

# Créer la table DOCLIGNE pour les achats en ajoutant la clé étrangère manquante
colonnes_docligne_achats = [c.copy() for c in docligne_ventes.columns]
colonnes_docligne_achats.append(
    Column("AF_REFFOURNISS", String(50), ForeignKey("ARTFOURNISS.AF_REFFOURNISS"), quote=True)
)
docligne_achats = Table("DOCLIGNE", metadata_achats, *colonnes_docligne_achats)